name: DEPLOY TO STAGING

on:
  push:
    branches:
      - develop

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Installing project dependencies
      - run: npm install
      - name: Building the project
      - run: npm run build
      - uses: appleboy/scp-action
          with:
            host: ${{ secrets.HOST}}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.SSHKEY }}
            port: ${{ secrets.PORT }}
            target: '/var/www/html/'